export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const INGREDIENTS_FETCH_FAIL = "INGREDIENTS_FETCH_FAIL"

export const PURCHASE_BURGER_SUCC = "PURCHASE_BURGER_SUCC"
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"