export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const INGREDIENTS_FETCH_FAIL = "INGREDIENTS_FETCH_FAIL"

export const PURCHASE_BURGER_SUCC = "PURCHASE_BURGER_SUCC"
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"
export const PURCHASE_INIT = "PURCHASE_INIT"

export const ORDERS_FETCH_START = "ORDERS_FETCH_START"
export const ORDERS_FETCH_SUCC = "ORDERS_FETCH_SUCC"
export const ORDERS_FETCH_FAIL = "ORDERS_FETCH_FAIL"

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REDIRECT = 'AUTH_REDIRECT';